.PHONY: clean All

All:
	@echo "----------Building project:[ Project2-9_Installation_and_Setup - Debug ]----------"
	@cd "Project2-9_Installation_and_Setup" && "$(MAKE)" -f  "Project2-9_Installation_and_Setup.mk"
clean:
	@echo "----------Cleaning project:[ Project2-9_Installation_and_Setup - Debug ]----------"
	@cd "Project2-9_Installation_and_Setup" && "$(MAKE)" -f  "Project2-9_Installation_and_Setup.mk" clean
